### ISSUE TITLE
Issues when used in the developer-rig

### ISSUE THREAD

**Issue by Serivy** [twitchdev/bot-commander#2]
When the developers rig clones the git repo via the template process it doesn't completely work because twitch-ext.js is missing from the html templates which mean onContext and onAuth do not fire.

I have modified panel.html and config.html to include this line
    
    <script src="https://localhost.rig.twitch.tv:3000/twitch-ext.js"></script>
and then the config panel loads (although configuration still doesn't load but i think that may be a dev-rig issue)

I also notice that the webpack is configured to use template.html to create these files but also doesn't include twitch-ext or get build as apart of the rig.

**Comment by lleadbet** [comment]
Sorry for the delay in getting to this issue. 

This is sort of intentional, as the devrig doesn't support this in local mode, only online mode (as configuration service isn't available for local mode extensions currently). 

Once that changes, I'm happy to get it working, however.
