### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by DaDummy** [twitchdev/bot-commander#3]
It seems that this sample project is currently only built for shell-based OSes like Mac and Linux, but since it is one of the sample projects for the Extension Developer Rig which in turn only supports Windows and Mac this effectively limits the usefulness of this sample to Mac only. ("yarn cert" tries to run a .sh-script)

Is there any chance of adding Windows support for this sample project?

**Comment by lleadbet** [comment]
Hello! We covered this in #2 , but the short version is that Windows support is added by using the developer-rig instead. 

We're still investigating adding Windows support for this project independently, however!
